APP_NAME = "MusicTimer Pro"
APP_VERSION = "0.1.0"

DEFAULT_INTERVAL_MINUTES = 15
DEFAULT_VOLUME = 80

DEFAULT_THEME = "dark"
DEFAULT_APPEARANCE_MODE = "dark"

MIN_INTERVAL_MINUTES = 1
MAX_INTERVAL_MINUTES = 1440

WINDOW_WIDTH = 1100
WINDOW_HEIGHT = 700
MIN_WINDOW_WIDTH = 900
MIN_WINDOW_HEIGHT = 600